"""Polish KW1 keys for print

Polish KW1 models generated by [keygen](https://github.com/ervanalb/keygen) so they can be printed and actually used.

More specifically,
- Cut it thinner to avoid overhang and size mismatch.
- Deepen the slot to avoid mismatch.

To generate `a.stl` for a KW1 key:

```
keygen scad/kwikset.scad --bitting 12345
```

CadQuery cannot import `.stl`. So `.stl` needs to be converted to `.step` first. To convert `.stl` to `.step` using FreeCAD:
- Open the `.stl` file.
- Switch to "Part" workspace.
- Part -> Create shape from mesh.
- Part -> Convert to solid.
- File -> Export.

The example `k1a` and `k1b` use bitting 12345 and 76543.
"""

import cadquery as cq
from cadquery import *
from functools import partial, reduce
import os


def union_all(objs):
    return reduce(lambda a, b: a.union(b), filter(None, objs))


def center(obj, x=None, y=None, z=None):
    # 0: center, -1: edge, 1: edge
    bbox = obj.val().BoundingBox()
    x_offset = y_offset = z_offset = 0
    if x is not None:
        x_offset = -(bbox.xmax + bbox.xmin) / 2
        x_offset += x * (bbox.xmax - bbox.xmin)
    if y is not None:
        y_offset = -(bbox.ymax + bbox.ymin) / 2
        y_offset += y * (bbox.ymax - bbox.ymin)
    if z is not None:
        z_offset = -(bbox.zmax + bbox.zmin) / 2
        z_offset += z * (bbox.zmax - bbox.zmin)
    return obj.translate((x_offset, y_offset, z_offset))


W = Workplane()


def k1polish(name):
    # created by ervanalb/keygen
    # converted by freecad (Part: "Create shape from mesh", "Convert to solid")
    v = cq.importers.importStep(name).val().Solids()[0]
    bbox = v.BoundingBox()
    # print(
    #     f"x={bbox.xmax - bbox.xmin}; y={bbox.ymax - bbox.ymin}; z={bbox.zmax - bbox.zmin}"
    # )
    # x = 2; y = 52.3239; z=21.7594
    v = Workplane(obj=v)
    v = center(v, x=0, y=0, z=0)
    c0 = W.box(0.4, 53, 22, centered=(True, True, True))
    c1 = c0.translate((1, 0, 0))
    c2 = c0.translate((-1, 0, 0))
    v = v.cut(c1).cut(c2)
    # move hang-over slot higher (deeper)
    b2 = W.box(1, 53, 1.5).translate((0.2, 0, -0.45))
    b2v = b2.cut(v)
    v = v.cut(b2v.translate((-0.3, 0, 0)))
    return v


def render():
    k1a = k1polish("k1a.step")
    k1b = k1polish("k1b.step")
    return k1a.union(k1b.translate((0, 0, 25)))


obj = render()
cq.exporters.export(obj, os.path.basename(__file__).split(".")[0] + ".stl")
show_object(obj)
